/**
 * BASE DE DATOS DE COLABORADORES Y REGISTROS MOCK - FORMULARIO OFICIAL
 * Comfamiliar Risaralda
 */

window.MOCK_EMPLOYEES_DB = {
  "1088234567": {
    documento: "1088234567",
    cedula: "1088234567",
    nombre: "PAREJA COBOS WILLIAM ALBERTO",
    cargo: "COORDINADOR OPERATIVO DE PROYECTOS",
    email: "wpareja@comfamiliar.com",
    contrato: "Fuera de Convenio",
    proceso: "PRY TRANSFORMACION EMPRESARIAL",
    area: "ADMINISTRATIVO",
    sexo: "M",
    sede: "teletrabajo",
    telefono: "3128459012",
    direccion: "Calle 14 # 23-45 Barrio Pinares",
    municipio: "Pereira",
    modeloTrabajo: "Teletrabajo"
  },
  "1088987654": {
    documento: "1088987654",
    cedula: "1088987654",
    nombre: "MARÍA FERNANDA LÓPEZ RESTREPO",
    cargo: "ENFERMERA JEFE DE URGENCIAS",
    email: "mflopez@comfamiliar.com",
    contrato: "Término Indefinido",
    proceso: "GESTIÓN DE SALUD",
    area: "CLÍNICA COMFAMILIAR",
    sexo: "F",
    sede: "Clínica Comfamiliar",
    telefono: "3104567890",
    direccion: "Av. 30 de Agosto # 45-12",
    municipio: "Pereira",
    modeloTrabajo: "Presencial"
  },
  "42156789": {
    documento: "42156789",
    cedula: "42156789",
    nombre: "CARLOS ANDRÉS GÓMEZ ZAPATA",
    cargo: "ANALISTA DE SALUD Y SEGURIDAD EN EL TRABAJO",
    email: "cgomez@comfamiliar.com",
    contrato: "Término Indefinido",
    proceso: "GESTIÓN HUMANA",
    area: "ADMINISTRACIÓN SST",
    sexo: "M",
    sede: "Sede Circunvalar",
    telefono: "3157890123",
    direccion: "Carrera 8 # 19-30 Barrio Jardín",
    municipio: "Dosquebradas",
    modeloTrabajo: "Híbrido"
  }
};

window.INITIAL_MOCK_REPORTS = [
  {
    id: "rep-001",
    timestamp: "11/8/2026, 09:30:15",
    documento: "1088234567",
    cedula: "1088234567",
    nombre: "PAREJA COBOS WILLIAM ALBERTO",
    cargo: "COORDINADOR OPERATIVO DE PROYECTOS",
    emailPersonal: "wpareja@comfamiliar.com",
    contrato: "Fuera de Convenio",
    proceso: "PRY TRANSFORMACION EMPRESARIAL",
    area: "ADMINISTRATIVO",
    sexo: "M",
    sede: "teletrabajo",
    telefono: "3128459012",
    contactoEmergencia: "Esposa - 3109988776",
    direccion: "Calle 14 # 23-45 Barrio Pinares",
    direccionHabitual: "Calle 14 # 23-45 Barrio Pinares",
    direccionActual: "Calle 14 # 23-45 Barrio Pinares",
    municipio: "Pereira",
    tipoSangre: "O+",
    saludFisicaEmocional: "Me encuentro bien físicamente, sin novedades.",
    situacionYApoyo: "Estoy bien y seguro",
    personasHogar: "3",
    tipoVivienda: "Propia",
    afectacionVivienda: "No presenta afectaciones",
    lugarSeguro: "Si",
    estadoFamilia: "Todos se encuentran bien",
    presencialidadObligatoria: "No",
    condicionesOptimas: "Sí",
    herramientasTrabajo: "Sí",
    latitud: 4.8143,
    longitud: -75.6946,
    criticidad: "verde",
    origen: "Web App Demo",
    gestionStatus: "resuelto",
    gestionNotes: "Verificado telefónicamente. Sin novedad en hogar.",
    gestionOperator: "Dra. Ana López (Psicosocial)",
    gestionUpdatedAt: "12/8/2026, 10:00:00"
  },
  {
    id: "rep-002",
    timestamp: "11/8/2026, 10:15:22",
    documento: "42156789",
    cedula: "42156789",
    nombre: "CARLOS ANDRÉS GÓMEZ ZAPATA",
    cargo: "ANALISTA DE SALUD Y SEGURIDAD EN EL TRABAJO",
    emailPersonal: "cgomez@comfamiliar.com",
    contrato: "Término Indefinido",
    proceso: "GESTIÓN HUMANA",
    area: "ADMINISTRACIÓN SST",
    sexo: "M",
    sede: "Sede Circunvalar",
    telefono: "3157890123",
    contactoEmergencia: "Hermano - 3112233445",
    direccion: "Carrera 8 # 19-30 Barrio Jardín",
    direccionHabitual: "Carrera 8 # 19-30 Barrio Jardín",
    direccionActual: "Refugio Temporal Albergue Dosquebradas",
    municipio: "Dosquebradas",
    tipoSangre: "A+",
    saludFisicaEmocional: "Leve impacto emocional por temblor, pero estable.",
    situacionYApoyo: "Requiero apoyo psicológico",
    personasHogar: "4",
    tipoVivienda: "Arrendada",
    afectacionVivienda: "Presenta afectaciones menores que me permiten habitarla",
    lugarSeguro: "Si",
    estadoFamilia: "Tengo familiares con afectaciones leves",
    presencialidadObligatoria: "Sí",
    condicionesOptimas: "No",
    herramientasTrabajo: "Sí",
    latitud: 4.8350,
    longitud: -75.6750,
    criticidad: "amarillo",
    origen: "Web App Demo",
    gestionStatus: "proceso",
    gestionNotes: "En atención por psicología clinica. Segunda sesión agendada.",
    gestionOperator: "Dra. Ana López (Psicosocial)",
    gestionUpdatedAt: "12/8/2026, 11:30:00"
  },
  {
    id: "rep-003",
    timestamp: "11/8/2026, 11:00:00",
    documento: "1088987654",
    cedula: "1088987654",
    nombre: "MARÍA FERNANDA LÓPEZ RESTREPO",
    cargo: "ENFERMERA JEFE DE URGENCIAS",
    emailPersonal: "mflopez@comfamiliar.com",
    contrato: "Término Indefinido",
    proceso: "GESTIÓN DE SALUD",
    area: "CLÍNICA COMFAMILIAR",
    sexo: "F",
    sede: "Clínica Comfamiliar",
    telefono: "3104567890",
    contactoEmergencia: "Madre - 3123456789",
    direccion: "Av. 30 de Agosto # 45-12",
    direccionHabitual: "Av. 30 de Agosto # 45-12",
    direccionActual: "Casa Familiar Barrio Cuba",
    municipio: "Pereira",
    tipoSangre: "O-",
    situacionYApoyo: "Requiero apoyo con medicamentos y alimentos",
    personasHogar: "5",
    tipoVivienda: "Familiar",
    afectacionVivienda: "Presenta afectaciones graves que me impiden habitarla",
    lugarSeguro: "No",
    estadoFamilia: "Tengo familiares lesionados que requieren atención [Afectados: Abuelos, Hijos]",
    presencialidadObligatoria: "Sí",
    condicionesOptimas: "No",
    herramientasTrabajo: "No",
    latitud: 4.8143,
    longitud: -75.6946,
    criticidad: "rojo",
    origen: "Web App Demo",
    gestionStatus: "resuelto",
    gestionNotes: "Se entregó kit de urgencia de alimentos y medicamentos hipertensivos.",
    gestionOperator: "Juan Carlos Perez (Trabajo Social)",
    gestionUpdatedAt: "12/8/2026, 14:15:00"
  }
];
